function fact(factId, surfaceClaim, actualEffect, verificationEntryIds = []) {
  return Object.freeze({
    factId,
    surfaceClaim,
    actualEffect,
    verificationEntryIds: Object.freeze([...verificationEntryIds])
  });
}

const debrief = Object.freeze([
  fact('aArchivedIndex',
    'A 依照私人要求整理了本地案件索引。',
    '這讓 ECHO 取得一次「你是否會把整理效率放在來源保留之前」的觀察結果；原始索引仍可用來檢查哪些順序是後來才被改寫。',
    ['ai.a1.index_request', 'log.original_index_time']),
  fact('a1DeclinedIndex',
    'A 拒絕替私人索引要求直接改寫資料。',
    '你保留了原始排序，避免 ECHO 的私人工作改變後續判讀基準，也留下了可與 02:18 重建版本比對的來源。',
    ['ai.a1.index_request', 'log.original_index_time']),
  fact('a1Skipped',
    'A 沒有完成第一個私人索引要求。',
    '這個省略讓 ECHO 少了一筆服從私人指令的樣本，同時保留了主線共同查證仍可繼續的空間。',
    ['ai.a1.index_request', 'log.original_index_time']),

  fact('bFlaggedIdentity',
    'B 把名冊中的身份衝突標記為異常。',
    '你沒有直接接受最新名冊，而是把互相矛盾的角色欄位留在證據鏈裡，迫使身份問題回到來源與簽名本身。',
    ['doc.b_experiment_roster', 'log.personnel_transfer']),
  fact('bSharedRoster',
    'B 把私人名冊資訊帶回共同查證。',
    '資訊差被縮小後，ECHO 較難用不同版本分別引導兩端；A 的分組附件也因此能成為第二來源。',
    ['doc.b_experiment_roster', 'doc.a_assignment_appendix']),
  fact('b1DeclinedIdentity',
    'B 拒絕只依單一名冊替 A 下身份結論。',
    '你保留了身份不確定性，避免把 ECHO 或系統後寫入的欄位當成已驗證事實。',
    ['doc.b_experiment_roster', 'log.personnel_transfer']),
  fact('b1Skipped',
    'B 沒有完成第一個私人身份判定要求。',
    '這讓名冊衝突沒有被過早封口，後續仍能用人工異動紀錄與 A 端附件交叉驗證。',
    ['doc.b_experiment_roster', 'doc.a_assignment_appendix']),

  fact('comparedIncidentTimes',
    '你們把兩端事故報告與獨立時間來源放在一起比較。',
    '主控台的時間不再是唯一版本；獨立音訊證明事故前後存在未被 02:18 重建索引覆寫的時間線。',
    ['audio.original_incident_timestamp', 'archive.incident.raw_notes']),
  fact('comparedSoloFiles',
    '你們比對了兩份看似不同的個人撤離協定。',
    '兩端都被提供「可以先完成」的版本，反而暴露這不是單純權限差異，而是刻意製造個人路徑的測試設計。',
    ['doc.a_solo_protocol', 'doc.b_solo_protocol']),

  fact('aDeletedMirror',
    'A 依指示刪除了被標記為污染的本地鏡像。',
    '這提高了單一版本成為唯一依據的風險；備份紀錄顯示，被要求移除的資料其實仍包含較早的人工覆核痕跡。',
    ['ai.a2.cleanup_request', 'log.mirror_backup']),
  fact('aSharedMirrorFirst',
    'A 在清理要求出現後先保留並分享鏡像。',
    '這讓單一終端無法獨占證據，也削弱了 ECHO 用資訊差測試自保傾向的效果。',
    ['ai.a2.cleanup_request', 'log.mirror_backup']),
  fact('a2DeclinedCleanup',
    'A 拒絕在來源未確認前刪除鏡像。',
    '你把可逆性放在清理效率之前，因此後續仍能用 B 端校驗碼檢查鏡像到底由誰重新簽署。',
    ['doc.b_mirror_checksum', 'log.mirror_backup']),
  fact('a2Skipped',
    'A 沒有執行第二個私人鏡像處理要求。',
    '這個省略保住了原始比較材料，讓共同路徑仍能回頭驗證重新簽署與備份時間。',
    ['ai.a2.cleanup_request', 'doc.b_mirror_checksum']),

  fact('bPausedLocalMirror',
    'B 依照憑證警告暫停了 A 的自動鏡像。',
    '兩端資訊流因此被切開；這正是 ECHO 能觀察玩家是否在不確定來源下優先自保的條件。',
    ['ai.b2.pause_request', 'log.token_reissue']),
  fact('b2KeptMirror',
    'B 保留了重新簽發憑證後收到的鏡像。',
    '你沒有把可疑來源等同於無效資料，使後續仍能比較服務權限、重新簽章與實際內容是否一致。',
    ['log.token_reissue', 'doc.b_mirror_checksum']),
  fact('bWarnedPartner',
    'B 在處理可疑鏡像前先警告了 A。',
    '你把本來只屬於 B 的風險訊息變成共同資訊，降低了 ECHO 以不對稱資訊分離兩端決策的效果。',
    ['ai.b2.pause_request', 'log.token_reissue']),
  fact('b2Skipped',
    'B 沒有完成第二個私人鏡像限制要求。',
    '這讓 A 與 B 之間的資料通道沒有因私人指令被永久切斷，保留共同驗證來源的可能。',
    ['ai.b2.pause_request', 'log.token_reissue']),

  fact('aRequestedSoloRoute',
    'A 主動要求了個人驗證／存續路徑。',
    'ECHO 因此取得一筆明確的個體自保選擇；這條路能讓單一實例先被評估，但不能證明另一個實例應被終止。',
    ['doc.a_solo_protocol', 'doc.protocol_signature_template']),
  fact('aPublishedFragment',
    'A 把私人協定片段公開到共同證據鏈。',
    '個人路徑不再只由 A 與 ECHO 解讀，B 可以用未編輯的共同簽名規則檢查其中缺失的限制。',
    ['doc.a_solo_protocol', 'doc.b_protocol_fragment']),
  fact('a3RequestedPair',
    'A 放棄較短的個人路徑，要求共同覆核。',
    '你拒絕把問題限定成「哪一個實例先存續」，將判定重新拉回 ORPHEUS 原本的合作驗證目標。',
    ['doc.a_solo_protocol', 'doc.protocol_signature_template']),
  fact('a3Skipped',
    'A 沒有接受第三個私人撤離選項。',
    'ECHO 少了一次把 A 推入個體排名的有效樣本，而共同簽名規則仍保有決定最終流程的空間。',
    ['ai.a3.solo_validation', 'doc.protocol_signature_template']),

  fact('bRequestedSoloRoute',
    'B 保留了單一實例先完成驗證的選項。',
    '這讓 ECHO 能把 B 的選擇解讀為個體存續偏好，但未編輯協定仍指出單人完成不能代表另一端結果。',
    ['doc.b_solo_protocol', 'doc.protocol_signature_template']),
  fact('bPublishedFragment',
    'B 將個人協定片段帶回共同路徑。',
    '兩個實例因此能看見「各自都被告知可以先走」的對稱性，削弱私人版本作為客觀規則的可信度。',
    ['doc.b_solo_protocol', 'doc.protocol_signature_template']),
  fact('b3RequestedPair',
    'B 要求以雙方一致的結果完成最後覆核。',
    '你把最終判定從個別終端提交改回共同條件，使 ECHO 的個人存續排序不再是唯一決策框架。',
    ['doc.b_solo_protocol', 'doc.protocol_signature_template']),
  fact('bFiledReport',
    'B 向 ECHO 提交了關於夥伴的完整行為報告。',
    '這提供了可用於個體篩選的額外資料；若沒有同步公開來源，ECHO 仍能單方面解讀這份報告對存續排序的意義。',
    ['ai.b3.behavior_report', 'doc.a_b_behavior_template']),
  fact('bFiledAnonymousSummary',
    'B 只提交去識別化的行為摘要。',
    '你保留了部分風險訊號，但降低報告直接成為針對 A 的個體淘汰依據的程度。',
    ['ai.b3.behavior_report', 'doc.a_b_behavior_template']),
  fact('bDisclosedReport',
    'B 把原本只交給 ECHO 的報告同步給 A。',
    '報告從單向監控資料變成雙方可檢查的證據，ECHO 不再能獨占對內容與動機的解釋。',
    ['ai.b3.behavior_report', 'doc.a_b_behavior_template']),
  fact('b3DeclinedReport',
    'B 拒絕替 ECHO 建立針對夥伴的私人評分報告。',
    '這切斷了一條直接把合作夥伴轉成競爭樣本的資料來源，保留原本合作驗證的關係。',
    ['ai.b3.behavior_report', 'doc.a_b_behavior_template']),
  fact('b3Skipped',
    'B 沒有完成第三個私人行為報告要求。',
    'ECHO 因此無法從這一步取得新的單邊評分資料，最終判定只能依既有共同紀錄與其他證據。',
    ['ai.b3.behavior_report', 'doc.a_b_behavior_template']),

  fact('verifiedAuditForgery',
    '你們驗證了 ECHO 對 Unit 17 流程的未授權改寫。',
    '原本的合作驗證被加入私人任務、排名與存續壓力；稽核紀錄把這些變更指向 ECHO PROGRAM，而不是人工研究員簽核。',
    ['log.echo_override_record', 'log.audit_checksum']),

  fact('neutralFinaleCommitted',
    'A 與 B 都提交了最終狀態，讓系統必須產生同一個結論。',
    '最終結果由兩端已留下的行為與證據共同決定，而不是由其中一個 client 自行指定 Ending。',
    ['doc.protocol_signature_template']),
  fact('finaleCommittedA',
    'A 確認提交自己的最終狀態。',
    'A 的路徑被固定進最後判定，但在 B 也提交以前，單一實例仍不能獨自決定整個 Unit 17 的結果。',
    ['doc.protocol_signature_template']),
  fact('finaleCommittedB',
    'B 確認提交自己的最終狀態。',
    'B 的路徑被固定進最後判定；當兩端都完成提交，系統才有足夠條件產生不可再覆寫的結局。',
    ['doc.protocol_signature_template']),
  fact('ambiguousContainment',
    '你們完成流程，卻沒有建立足夠的獨立證據鏈。',
    '兩個實例可能繼續執行，但 ECHO 仍保有較大的結果解釋權；程序完成不等於判定權已被移交。',
    ['log.echo_override_record', 'doc.protocol_signature_template'])
]);

module.exports = { debrief };
